### ISSUE TITLE
Linux: auto activation

### ISSUE THREAD

**Issue by btro1404** [tykefcz/IniIno#2]
Thank you for this great project!
I'm useing Arduino 1.8.13 in Ubuntu (both languages: german) and it works fine except of "Auto activate first board after sketch load". Even if a board is in the sketch and this option is marked it doesn't change the settings. Manually activation in `Tools > Project boards` works.

**Comment by tykefcz** [comment]
Thanks for testing.
Bug was in two names in preferences file - from UI differ than from autoload check.
Repaired in 0.7

**Comment by btro1404** [comment]
That works, Thank you!
